name: Manual Release APK (Stable Versions)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.1)'
        required: true
        default: '1.0.0'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: "platform-tools platforms;android-34 build-tools;34.0.0"

      - name: Build debug APK
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon clean assembleDebug
      
      - name: Rename APK for release
        run: |
          cp app/build/outputs/apk/debug/app-debug.apk basketball-stats-v${{ github.event.inputs.version }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Basketball Stats v${{ github.event.inputs.version }}
          body: |
            🏀 Basketball Statistics App - Debug Build
            
            **Installation Instructions:**
            1. Download the APK file below
            2. Enable "Install from unknown sources" in your Android settings
            3. Install and enjoy!
            
            Built from commit: ${{ github.sha }}
          files: basketball-stats-v${{ github.event.inputs.version }}.apk
          draft: false
          prerelease: false
