name: Release APK

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          # space-separated list prevents parsing error
          packages: "platform-tools platforms;android-34 build-tools;34.0.0"

      - name: Build release APK
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon clean assembleRelease

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: Automated release from push to main.
          files: app/build/outputs/apk/release/app-release-unsigned.apk
